In [1]:
# In the world of data science , mastering pandas Is like learning to read before writing poetry

In [2]:
# Use of Pandas ================
# data cleaning , 
# data analyse  ,
# data ,manipulation ,
# data transformation  
# data visualization 
# data aggregation ,
# file handilng ,
# data filtering and selection ,
# time series analysis...

In [3]:
# What are we going to learn in pandas = 
# Series 
# dataframes 
# missing data 
# merging joining concatination 
# group by and aggregations 
# pivot tables and crosstab
# operations 
# some great capstone project
#

# Pandas Series

In [4]:
# A Series is a one-dimensional labeled array capable of holding any data type . The axis labels are collectively called the index

Creating Series 
There are multiple ways to create a pandas Series :

In [5]:
import numpy as np 
import pandas as pd

In [6]:
# age = [20 , 34 , 32 , 54]
# sub = ["physics","chemistry","math","Biology"]
# name = ["Shubham","keten","sarthak","Paraju"]
# occu = ["Doctor","Engineer","pilot","Artist"]
# sr_no = [1 , 2 , 3 , 4]


# pd.Series(age)
# pd.Series(name)
# pd.Series(occu)

labels = ["a","b","c"]
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:2,2:20,3:30}

In [7]:
pd.Series(my_list) # In pandas Series method is use for giving the number series to the data

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(my_list, index = labels) # data = my_list , index = labels 
                                 # Element of lables list is for the index 

pd.Series(labels, index = arr)

10    a
20    b
30    c
dtype: object

In [9]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [10]:
pd.Series(d)

1     2
2    20
3    30
dtype: int64

In [11]:
pd.Series(labels,index = d)

1    a
2    b
3    c
dtype: object

# DataFrames

In [12]:
# Dataframe = When you combine multiple Series Together so it forms is called dataframes

# DataFrames Topic 
--> 1.Creating a DataFrames 
--> 2.Selection and indexing of coloumn 
--> 3.Creating new column 
--> 4.Removing Coloumn 
--> 5.Selecting Rows 
--> 6.Selecting Subsets of Rows and coloumns 
--> 7.Conditional Selection

# --------

Creating a DataFrame

In [13]:
data = {
    "Name" : ["john","Anna","Peter","Linda"],
    "age"  : [28, 38, 29, 42],
    "City" : ["New York","Paris","Berlin","London"],
    "Salary": [6500,70000,62000,85000]
}

df = pd.DataFrame(data)    # This for the dictionary
df

    Name  age      City  Salary
0   john   28  New York    6500
1   Anna   38     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# IN THE TABLE THERE ARE MULTIPLE COLLECTIONS OF THE SERIES SO --- IT IS CALLED AS TABLE

In [14]:
data_list = [
    ["john",28,"New York",65000],
    ["Anna",34,"Paris",70000],
    ["Peter",29,"Berlin",62000],
    ["Linda",42,"London",85000], 
]

df2 = pd.DataFrame(data_list)    # For the list
df2
# columns  = ["Name","Age","City","salary"]
# df2 = pd.DataFrame(data_list,columns = columns)
# df2

       0   1         2      3
0   john  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [15]:
heading = ["Name","Age","City","Salary"]    # Coloumn is use for coloumnv value 
df2 = pd.DataFrame(data_list,columns = heading)
df2

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# --

Selection and Indexing of columns

In [16]:
df2

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [17]:
df2["Name"]  # Syntax is used to access  the perticular coloumn of he table

0     john
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [18]:
df2["Age"]

0    28
1    34
2    29
3    42
Name: Age, dtype: int64

In [19]:
df2["City"]

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [20]:
# For selecting the multiple coloumns from dataframes 
df2[["Name","City"]]

    Name      City
0   john  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [21]:
df2[["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000
2    Berlin   62000
3    London   85000

# ---

Creating a new column

In [22]:
df2

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [23]:
# For creating new coloumn to the dataframes 
df2["Designation"] = ["Doctor","Eng","Doctor","Eng"]

# jevdhya values required ahet tevdhya values pass karaychya 
df2   # New coloumn is created 
      # imp - jevdhya Rows ahet tevhdyach values pass karaychya - ["Doctor","Eng","Doctor","Eng"]

    Name  Age      City  Salary Designation
0   john   28  New York   65000      Doctor
1   Anna   34     Paris   70000         Eng
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000         Eng

# ---

Removing Coloumn

# ---

In [24]:
# Bro in pandas the ,,axis = 1,,is coloumn AND axis = 0 is row ------------- numpy me opposite hota hai bhai

# df2.drop("Designation",axis = 1)
# df2
# Look Designation Coloumn is still there ,, Still it is not deleted .
df2.drop("Designation",axis = 1,inplace = True)
df2



# inplace = True - this keyword argument is used to delete perticular thing permentaly

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [25]:
# For removing the multiple Coloumns from the Table 
df2.drop(["City","Salary"],axis = 1)

    Name  Age
0   john   28
1   Anna   34
2  Peter   29
3  Linda   42

In [26]:
df2

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#  --

Removing Row

In [27]:
df2

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
df2.drop(0,axis = 0) 
# 0 row is deleted from the table -- but is is not deleted permently .. SO ,
                                                                           # if You want to delete it permently use --- inplace = True

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [29]:
df2.drop(2,axis = 0 )  # 2 Row is deleted

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
3  Linda   42    London   85000

In [30]:
df2

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [31]:
# Delete the multiple Rows 
df2.drop([2,3],axis = 0 )  # Pass the index in the list

   Name  Age      City  Salary
0  john   28  New York   65000
1  Anna   34     Paris   70000

# ---

Selecting Row

In [32]:
df2

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [33]:
df2.loc[0]   # loc stands for location - 
             # IT is use to select the rows of the of the table

Name          john
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [34]:
# Multiple Rows 
df2.loc[[0,1]]  #double square bracket to select the multiple Rows

   Name  Age      City  Salary
0  john   28  New York   65000
1  Anna   34     Paris   70000

In [35]:
# 1 more method - 
df2.iloc[3]        # iloc stands for == index location

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

# ----

Selecting Subsets of Rows and Coloumns

# ---

In [36]:
df2

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [37]:
df2.loc[[0,1]][["City","Salary"]]  # Selectiong the perticular portion of the table

       City  Salary
0  New York   65000
1     Paris   70000

In [38]:
df2

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [39]:
df2.loc[[2,3]][["Name","Age"]]   #  2 ,3 is the row name , Name and Age is Coloumn

    Name  Age
2  Peter   29
3  Linda   42

# ---

Conditional Selection

# --

In [40]:
df2

    Name  Age      City  Salary
0   john   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [41]:
# I only want to see those people whose Age above 30 
df2[df2["Age"] > 30]  # the Age over 30

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [42]:
# I only want to see those people whose Age above 30 and city must be paris
df2[(df2["Age"] > 30 ) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

# ---

# Missing Data

# --

In [43]:
import numpy as np  
import pandas as pd

Finding Missing Data

In [44]:
data = {
    "A" : [1, 2, np.nan, 4, 5],
    "B" : [np.nan, 2, 3, 4, 5],
    "C" : [1, 2, 3, np.nan, np.nan],
    "D" : [1,np.nan,np.nan,np.nan, 5],   
}
df = pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [45]:
df.isna()   # If the value is null then is False

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [46]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [47]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [48]:
df.isna().any()   # to check sabme NULL value hai  (True = ahe)

A    True
B    True
C    True
D    True
dtype: bool

# --

Removing missing value

# --

In [49]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [50]:
# It removies the data with the basis of rows

df.dropna()   # Removes a Row which has the Null value

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [51]:
# 40 min Youtube

In [52]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [53]:
df.dropna(thresh = 3)  # Mininum required 3 non-null values

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

In [54]:
df.dropna(thresh = 2) # Minimum non_null (numbers) required in row

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [55]:
df.dropna(thresh = 5)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

# --

Filling the missing data

In [56]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [57]:
df.fillna(0)  # It fills the null values with 0   (replace 0 Nan with 0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [58]:
df.fillna(3)  # Fill na with 3 number

     A    B    C    D
0  1.0  3.0  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  3.0  3.0
4  5.0  5.0  3.0  5.0

In [59]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [60]:
values = {"A" : 0, "B" : 100 ,"C" : 300 , "D": 400} # DICTIONARY
df.fillna(value  = values) # value is the keyword of pandas 
# A =  0  , B = 100 , C = 300 , D = 400  It replace the value of the given named coloumn

     A      B      C      D
0  1.0  100.0    1.0    1.0
1  2.0    2.0    2.0  400.0
2  0.0    3.0    3.0  400.0
3  4.0    4.0  300.0  400.0
4  5.0    5.0  300.0    5.0

In [61]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [62]:
df.fillna(df.mean())  #  # It gives the means of the of the each row of the coloumn

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0

# Merging Joining Concatination

In [63]:
import numpy as np 
import pandas as pd

# --

Merging 2 dataframes

In [64]:
employees = pd.DataFrame({
    "employees_id" : [1, 2, 3, 4, 5],
    "name" : ["John", "Anna", "Peter", "Linda", "Bob"],
    "department" : ["HR","IT","Finance","IT","HR"],
})

# DataFrame 2 : Salary information 
salaries = pd.DataFrame({
    "employees_id" : [1, 2, 3, 6, 7],
    "salary" : [60000, 80000, 65000, 70000, 90000],
    "bonus" : [5000, 10000, 7000, 8000, 12000],
    
})

In [65]:
employees

   employees_id   name department
0             1   John         HR
1             2   Anna         IT
2             3  Peter    Finance
3             4  Linda         IT
4             5    Bob         HR

In [66]:
salaries

   employees_id  salary  bonus
0             1   60000   5000
1             2   80000  10000
2             3   65000   7000
3             6   70000   8000
4             7   90000  12000

In [67]:
pd.merge(employees,salaries,on="employees_id",how ="inner")  # It is use to merge 2 dataFrames

                                                            # on = "employee_id" -----> it is use to merge two dataFrames on common coloumn = employee_id 
                                                             #  Basis of Row

   employees_id   name department  salary  bonus
0             1   John         HR   60000   5000
1             2   Anna         IT   80000  10000
2             3  Peter    Finance   65000   7000

In [68]:
pd.merge(employees,salaries,on="employees_id",how ="outer") 

# outer --- > ON THE BASIS OF COLOUMN

   employees_id   name department   salary    bonus
0             1   John         HR  60000.0   5000.0
1             2   Anna         IT  80000.0  10000.0
2             3  Peter    Finance  65000.0   7000.0
3             4  Linda         IT      NaN      NaN
4             5    Bob         HR      NaN      NaN
5             6    NaN        NaN  70000.0   8000.0
6             7    NaN        NaN  90000.0  12000.0

In [69]:
pd.merge(employees,salaries,on="employees_id",how ="left")

   employees_id   name department   salary    bonus
0             1   John         HR  60000.0   5000.0
1             2   Anna         IT  80000.0  10000.0
2             3  Peter    Finance  65000.0   7000.0
3             4  Linda         IT      NaN      NaN
4             5    Bob         HR      NaN      NaN

In [70]:
pd.merge(employees,salaries,on="employees_id",how ="right")

   employees_id   name department  salary  bonus
0             1   John         HR   60000   5000
1             2   Anna         IT   80000  10000
2             3  Peter    Finance   65000   7000
3             6    NaN        NaN   70000   8000
4             7    NaN        NaN   90000  12000

Concatination of 2 dataframes

In [71]:
df1 = pd.DataFrame({
    "A" : ["A0", "A1", "A2"],
    "B" : ["B0", "B1", "B2"],
    "C" : ["C0", "C1", "C2"],
})
df2 = pd.DataFrame({
    "A" : ["A3", "A4", "A5"],
    "B" : ["B3", "B4", "B5"],
    "C" : ["C3", "C4", "C5"],
})

In [72]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [73]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [74]:
pd.concat([df1,df2])       # Common of the 2 DataFrames -- after execution it remains common 
                        # Concate Row wise

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [75]:
# Rows 
pd.concat([df1,df2],axis = 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

Joining 2 Data frames

In [76]:
df1 = pd.DataFrame({
    "name": ["Alice","Bob","Charlie"]
}, index= [1, 2, 3] )

# Second DataFrame
df2 = pd.DataFrame({
    "score" : [85, 90, 75]
}, index = [2, 3, 4])

In [77]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [78]:
df2

   score
2     85
3     90
4     75

In [79]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [80]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

# Group_By_Aggregation

In [81]:
import numpy as np 
import pandas as pd

GroupBy

In [82]:
data = {
    "Category" : ["A","B","A","B","A","B","A","B"],
    "Store" : ["S1","S1","S2","S2","S1","S2","S2","S1"],
    "Sales" : [100, 200, 150, 250, 120, 180, 200, 300],
    "Date"  : pd.date_range("2023-01-01", periods = 8)
}
df = pd.DataFrame(data)

In [83]:
# Group by Category and calculatate the sum of sales 
cat = df.groupby("Category")["Sales"].sum()
cat 

# Sum of individual A , B sales

Category
A    570
B    930
Name: Sales, dtype: int64

In [84]:
# Group by store and calculation the sum of sales 
cat = df.groupby("Store")["Sales"].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [85]:
# Group by multiple coloumns 
# Group by category and store
cat = df.groupby(["Category","Store"])["Sales"].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

Aggregation

In [86]:
# In Aggregation there are , Mean , median , Std , count   .... etc

In [87]:
df

  Category Store  Sales       Date
0        A    S1    100 2023-01-01
1        B    S1    200 2023-01-02
2        A    S2    150 2023-01-03
3        B    S2    250 2023-01-04
4        A    S1    120 2023-01-05
5        B    S2    180 2023-01-06
6        A    S2    200 2023-01-07
7        B    S1    300 2023-01-08

In [88]:
df["Sales"].mean()   # Mean

np.float64(187.5)

In [89]:
df

  Category Store  Sales       Date
0        A    S1    100 2023-01-01
1        B    S1    200 2023-01-02
2        A    S2    150 2023-01-03
3        B    S2    250 2023-01-04
4        A    S1    120 2023-01-05
5        B    S2    180 2023-01-06
6        A    S2    200 2023-01-07
7        B    S1    300 2023-01-08

In [90]:
df["Sales"].agg(["sum","mean","min","max","count","std","median"])

# agg function is used to calculate the all mathematical operations OR statistical operation of all function it is called as agg function 
# agg functon me sabhi mathematical operation ek sath execute kar sakte hai ....

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

# --

# Piviot Table

# --

In [91]:
import numpy as np 
import pandas as pd

In [92]:
# Pivot Tables

In [93]:
data = {
    "Date" : pd.date_range("2023-01-01",periods = 20),
    "Product" : ["A","B","C","D"] * 5,
    "Region" : ["East","West","North","South","East","West","North","South","East","West",
                 "North","South","East","West","North","South","East","West","North","South"],
    "Sales" : np.random.randint(100 , 1000, 20),
    "Units" : np.random.randint(10,100,20),
    "Rep" : ["John", "Mary", "Bob", "Alice","John", "Mary", "Bob", "Alice","John", "Mary",
             "Bob", "Alice","John", "Mary", "Bob", "Alice","John", "Mary", "Bob", "Alice",]
}

df = pd.DataFrame(data)

df["Month"] = df["Date"].dt.month_name()
df["Quarter"] = "Q" + df["Date"].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    847     38   John  January      Q1
1  2023-01-02       B   West    871     51   Mary  January      Q1
2  2023-01-03       C  North    174     43    Bob  January      Q1
3  2023-01-04       D  South    978     71  Alice  January      Q1
4  2023-01-05       A   East    842     49   John  January      Q1
5  2023-01-06       B   West    831     55   Mary  January      Q1
6  2023-01-07       C  North    891     70    Bob  January      Q1
7  2023-01-08       D  South    866     69  Alice  January      Q1
8  2023-01-09       A   East    366     74   John  January      Q1
9  2023-01-10       B   West    817     56   Mary  January      Q1
10 2023-01-11       C  North    310     14    Bob  January      Q1
11 2023-01-12       D  South    300     16  Alice  January      Q1
12 2023-01-13       A   East    665     21   John  January      Q1
13 2023-01-14       B   West    181     95   Mary  January      Q1
14 2023-01-15       C  North    407     73    Bob  January      Q1
15 2023-01-16       D  South    987     14  Alice  January      Q1
16 2023-01-17       A   East    279     35   John  January      Q1
17 2023-01-18       B   West    982     69   Mary  January      Q1
18 2023-01-19       C  North    289     27    Bob  January      Q1
19 2023-01-20       D  South    378     23  Alice  January      Q1

In [94]:
pd.pivot_table(df,values = "Sales",index = "Region", columns = "Product",aggfunc= "median") # When you dont give the aggfunction so it takes the mean by default

Product      A      B      C      D
Region
East     665.0    NaN    NaN    NaN
North      NaN    NaN  310.0    NaN
South      NaN    NaN    NaN  866.0
West       NaN  831.0    NaN    NaN

In [95]:
pivot2 = pd.pivot_table(df, values = ["Sales","Units"] , index = "Region", columns = "Product")
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     599.8    NaN    NaN    NaN  43.4   NaN   NaN   NaN
North      NaN    NaN  414.2    NaN   NaN   NaN  45.4   NaN
South      NaN    NaN    NaN  701.8   NaN   NaN   NaN  38.6
West       NaN  736.4    NaN    NaN   NaN  65.2   NaN   NaN

Cross Tabs

In [96]:
pd.crosstab(df["Region"],df["Product"])  # Crosstab is for counting purpose

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# --

# Operations

# --

DataFrames Basic Operations

In [97]:
import numpy as np 
import pandas as pd

In [98]:
df1 = pd.DataFrame({
    "A" : [1, 2, 3, 4, 5],
    "B" : [10, 20, 30, 40, 50],
    "C" : [100, 200, 300, 400, 500]
})

In [99]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [100]:
df1.shape   # To identifing the shape of the dataFrames

(5, 3)

In [101]:
df1.columns   # Which are the coloumns

Index(['A', 'B', 'C'], dtype='object')

In [102]:
df1.info          # Informations of the dataframes

<bound method DataFrame.info of    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500>

In [103]:
df1.describe()     # To describe the informations 
                  #   it shows the count , mean , std , min , 25% , 75% , max

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [104]:
df1["A"] + 10      # To add the 10 to each vaue of A columns

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [105]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [106]:
def square(x):
    return x ** 2

In [107]:
df1["B"].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [108]:
#for changes in main dataframes 
df1["B"] = df1["B"].apply(square)
df1

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500

In [109]:
# 1 : 28 yOUTUBE vIDEO 
# REAL WORLD PROBLEM START

 # --- Feature Extraction  ----

In [110]:
# Load the data

# Anime project

In [111]:
import numpy as np 
import pandas as pd

In [112]:
df = pd.read_csv(r"anime.csv")
df

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

In [113]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [114]:
# Question - 

# Make a new column for episode count 
# make a new coloumn for time stamp 
# which anime hass the height score 
# give me top 5 highest scoring score 
# which anime has the heighest episode count 
# animes wth top 5 episode count 
# Which is the longest running

In [115]:
df.loc[1]

Rank                                                     2
Title    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
Score                                                 9.07
Name: 1, dtype: object

In [116]:
df.loc[2]["Title"]

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [117]:
df

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

In [118]:
# Make a new column for episode count  

def extract_episodes(txt):
    data = ""
    check = False

    for i in txt:
        if i == "(":
            check = True

        elif i == ")":
            check = False
            return data

        elif check == True:
            data = data + i

In [119]:
df["Episodes"] = df["Title"].apply(extract_episodes)

In [120]:
df["Episodes"] = df["Episodes"].str.replace("eps","")  # for removing the eps word from the episodes because for aggregation function [ min , max] etc ..
df  # the episodes numbers is still in string

    Rank                                              Title  Score Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10      64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07      24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06      13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06      51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05      10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04      51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04       1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04     148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04      13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03      13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03       2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02     110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99      13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99      13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98      12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94     201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94       1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93      22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93      24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91      25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91       1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89       1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88       7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88      14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87      74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84       1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84       1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83      12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83       1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82      24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82      23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81      12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81      26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80      13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80      16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79      11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79       1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79      11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78      10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78       1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77      26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77      12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76      75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75      26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75      26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74      24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73      10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72      12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71      12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71       4

In [121]:
df["Episodes"] = df["Episodes"].astype(int)   # astype function is use to conversion of the data

In [122]:
df

    Rank                                              Title  Score  Episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04        51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04         1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04       148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04        13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03        13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03         2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02       110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99        13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99        13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98        12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94       201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94         1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93        22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93        24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91        25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91         1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89         1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88         7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88        14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87        74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84         1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84         1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83        12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83         1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82        24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82        23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81        12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81        26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80        13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80        16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79        11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79         1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79        11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78        10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78         1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77        26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77        12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76        75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75        26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75        26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74        24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73        10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72        12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71        12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71         4

In [123]:
# Question 2 = 
# make a new coloumn for time stamp

def extraction_time(txt): 
    check = False
    data = ""
    for i in range(len(txt)): 
        if txt[i] == ")": 
            for j in range(i+1, i + 20): 
                data += txt[j] 
            return data

In [124]:
df["Total Time"] = df["Title"].apply(extraction_time)
df

,Rank,Title,Score,Episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999

In [125]:
# which anime hass the height score 
df[df["Score"] == df["Score"].max()]

,Rank,Title,Score,Episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010

In [126]:
# give me top 5 highest scoring anime 
df["Title"].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: object

In [127]:
# Which anime has the episode count 
df[df["Episodes"] == df["Episodes"].max()]

,Rank,Title,Score,Episodes,Total Time
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010

In [128]:
# anime with top 5 episode count 

df.sort_values('Episodes', ascending=False).head(5)

,Rank,Title,Score,Episodes,Total Time
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005

In [129]:
# Which is the longhest runtime anime 
df.sort_values('Episodes', ascending=False).head(1)

,Rank,Title,Score,Episodes,Total Time
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010

# End of the project

# ---- Project 2 ---

In [130]:
# Country project

In [132]:
# 1 : 54 Min lecture

In [133]:
import numpy as np 
import pandas as pd

In [146]:
df = pd.read_csv(r"Countries.csv")
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [145]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [ ]:
# Questions - 
# Which country has the highest population 
# what is the capital of the country with highest population
# Which country has the leasse population  
# What is the capital of the country with least population 
# give me top 5 countries with hieghest democratic score 
# how many country lie in Eastern Europe region 
# who is the pokitical leader of the 2nd hifhest populated country

In [147]:
# Which country has the highest population

df[df["population"] == df["population"].max()]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
75,India,Republic of India,Indian rupee,New Delhi,Southern Asia,Asia,Indian,20.0,77.0,1790450.0,...,1417173173,14.9446,908804812,508368361,1.71,7.23,Flawed democracy,23.9,Narendra Modi,Prime Minister

In [155]:
# least population country from the sheet 
df[df["population"] == df["population"].min()]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
179,Tuvalu,Tuvalu,Australian dollar,Funafuti,Polynesia,Oceania,Tuvaluan,-8.0,178.0,18.0,...,11312,6.25,3900,7412,0.0,0.0,Unknown,21.0,Kausea Natano,Prime Minister

In [160]:
# What is the capital of the country with least population 

df[df["population"] == df["population"].min()]["capital_city"]

179    Funafuti
Name: capital_city, dtype: object

In [175]:
# give me top 5 countries with heigest democratic score  
df.sort_values("democracy_score",ascending = False , inplace= True)
df["country"].head()

127         Norway
74         Iceland
164         Sweden
122    New Zealand
46         Denmark
Name: country, dtype: object

In [182]:
# How many region are there 
df["region"].value_counts().count()

np.int64(22)

In [186]:
# How many countries lie in Rastern Europe region 
df[df["region"] == "Eastern Europe"]["country"]

43      Czech Republic
151    Slovak Republic
24            Bulgaria
136             Poland
73             Hungary
139            Romania
111            Moldova
181            Ukraine
14             Belarus
140             Russia
Name: country, dtype: object

In [196]:
# who is the poltical leader of the 2nd highest populated country 

df[df["population"] == df["population"].nlargest(2).iloc[1]]["political_leader"]

34    Xi Jinping
Name: political_leader, dtype: object

In [200]:
# how many countries are there whose political leaders are unknown 
df[df["political_leader"].isna()]["country"] #.count()

27                         Cabo Verde
172                       Timor-Leste
151                   Slovak Republic
190                West Bank and Gaza
161    St. Vincent and the Grenadines
159               St. Kitts and Nevis
160                         St. Lucia
Name: country, dtype: object

In [201]:
# how many country have Republic in theire full name 
count = 0

def counting(txt): 
    global count 
    if "republic" in txt.lower(): 
        count = count + 1 
    return txt 

df['country_long'] = df["country_long"].apply(counting)
print(count)

125

In [210]:
# which country in african region has heighest population 
african_df = df[df["continent"] == "Africa"]

In [211]:
african_df[african_df["population"] == african_df["population"].max()]["country"]

125    Nigeria
Name: country, dtype: object